# Generated by Django 5.2 on 2025-04-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(default='English', max_length=20)),
                ('cover_image', models.ImageField(blank=True, help_text='Upload book cover image', null=True, upload_to='static/images/')),
            ],
        ),
    ]
