# Generated by Django 5.2 on 2025-04-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='added_to_website',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='age_group',
            field=models.CharField(choices=[('under_8', 'Under 8'), ('8_15', '8-15'), ('adults', 'Adults')], default='adults', max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
